// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func app() string {
	foo := NewFoo()
	bar := NewBar()
	v := ProvideNamers(foo, bar)
	string2 := ProvideNames(v)
	return string2
}
